In [1]:
import numpy as np

## Question 1

In [2]:
matrix_A = np.array([[1.,-1.,4.,0.,2.,9.],
                     [0.,5.,-2.,7.,8.,4.],
                     [1.,0.,5.,7.,3.,-2.],
                     [6.,-1.,2.,3.,0.,8.],
                     [-4.,2.,0.,5.,-5.,3.],
                     [0.,7.,-1.,5.,4.,-2.]])
matrix_b = np.array([[19.],
                     [2.],
                     [13.],
                     [-7.],
                     [-9.],
                     [2.]])

In [3]:
from comp_phy import Gauss_Jordan as GJ

In [4]:
matrix_Ab = GJ.make_aug(matrix_A, matrix_b)

In [5]:
print(matrix_Ab)

[[ 1. -1.  4.  0.  2.  9. 19.]
 [ 0.  5. -2.  7.  8.  4.  2.]
 [ 1.  0.  5.  7.  3. -2. 13.]
 [ 6. -1.  2.  3.  0.  8. -7.]
 [-4.  2.  0.  5. -5.  3. -9.]
 [ 0.  7. -1.  5.  4. -2.  2.]]


In [6]:
Gauss_Ab = GJ.Gauss_Jordan(matrix_Ab)          #return two values: [0]: Gauss_decomp and [1]: determinant

In [7]:
row = len(Gauss_Ab[0])                         #to recover the solved value of x from Gauss_decomp
GJ_solve_x = np.zeros((row,1))
mat = Gauss_Ab[0]
                      
for i in range(row):
    GJ_solve_x[i] = mat[i][row]
print(GJ_solve_x)

[[-1.761817043998]
 [ 0.896228033874]
 [ 4.051931404116]
 [-1.61713080254 ]
 [ 2.041913538502]
 [ 0.151832487156]]


In [8]:
from comp_phy import LU_decomp as LU

In [9]:
LU_A = LU.LU_decomp(matrix_A)

In [10]:
LU_solve_x = LU.solve_LU(LU_A,matrix_b)

In [11]:
print(LU_solve_x)

[[-1.761817043998]
 [ 0.896228033874]
 [ 4.051931404116]
 [-1.61713080254 ]
 [ 2.041913538502]
 [ 0.151832487156]]


In [12]:
from comp_phy import Jacobi as Jac

In [13]:
Jac_solve_x = Jac.Jacobi(matrix_A,matrix_b)

Solution not possible, method diverges
comp  379.4453333333333
comp  379.4453333333333


In [14]:
print(Jac_solve_x)

[  79.826666666667   83.992            63.144           -22.293333333333
  -49.816          -122.613333333333]


In [15]:
from comp_phy import Gauss_Seidel as GS

In [16]:
GS_solve_x = GS.Gauss_Seidel(matrix_A,matrix_b)

Solution not possible, method diverges.
comp  315.42


In [17]:
print(GS_solve_x)

[  19.      0.4    -1.2   -39.4   -52.64 -202.78]


## Question 2

In [18]:
from fractions import Fraction as frac

In [19]:
matrix_A2 = np.array([[2.,-3.,0.,0.,0.,0.],
                      [-1.,4.,-1.,0.,-1.,0.],
                      [0.,-1.,4.,0.,0.,-1.],
                      [0.,0.,0.,2.,-3.,0.],
                      [0.,-1.,0.,-1.,4.,-1.],
                      [0.,0.,-1.,0.,-1.,4]])
matrix_b2 = np.array([[frac(-5,2)],
                       [frac(2,3)],
                       [3],
                       [frac(-4,3)],
                       [frac(-1,3)],
                       [frac(5,3)]])

In [20]:
GS_solve_x2 = GS.Gauss_Seidel(matrix_A2,matrix_b2)

comp  8.2923732851653e-05


In [21]:
print("Solution via Gauss Seidel Method")
print(GS_solve_x2)

Solution via Gauss Seidel Method
[-1.112611615561  0.091604923712  0.927840687828 -0.83987389271
 -0.115461118682  0.619761558953]


In [22]:
Jac_solve_x2 = Jac.Jacobi(matrix_A2,matrix_b2)

comp  9.443554864833892e-05


In [23]:
print("Solution via Jacobi Method")
print(Jac_solve_x2)

Solution via Jacobi Method
[-1.112546864166  0.091621561443  0.927851667382 -0.839843393421
 -0.115436161356  0.619765147091]


In [24]:
from comp_phy import Conjugate_Gradient as CG

In [25]:
mat_b2=np.array([frac(-5,2),frac(2,3),3,frac(-4,3),frac(-1,3),frac(5,3)])

In [26]:
x0 = np.array([-1,-2,-1,1,-2,2])
CG_solve_x2 = CG.Conjugate_Gradient(matrix_A2, mat_b2, x0)

Iteration: 30000 	 x = [-1.1121109819220596 0.09170839725948181 0.9279459071497012
 -0.8400492681207176 -0.11564302102769031 0.6196048073295278] 	 residual = 0.0011

Solution: 	 x = [-1.1121109819220596 0.09170839725948181 0.9279459071497012
 -0.8400492681207176 -0.11564302102769031 0.6196048073295278]
